image: "node:latest"

stages:
  - install
  - build
  - publish

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm install
  only:
    - /^TR_/
    - dev
    - master
    - mobile-app-interface

build:
  stage: build
  script:
    - npm run release:build
  cache:
    paths:
      - dist/
  only:
    - /^TR_/
    - dev
    - master
    - mobile-app-interface

publish:
  stage: publish
  script:
    - npm publish
  only:
    - master
    - mobile-app-interface
